name: flutter_clean_architecture
description: "A template project for Flutter Clean Architecture project using BLOC pattern"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  build_runner: ^2.4.14
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  equatable: ^2.0.7
  flutter_bloc: ^8.1.6
  get_it: ^8.0.3
  json_annotation: ^4.9.0
  path_provider: ^2.1.5
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.2

flutter:
  uses-material-design: true